apiVersion: v1
name: react-sockjs-keycloak
description: REPLACE_ME_APP_DESCRIPTION
version: 1.0.0
keywords:
  - stakater
  - javascript
home: REPLACE_ME_GITHUB_LINK
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
